require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.bufferline"
require "user.telescope"
require "user.nvim-tree"
require "user.treesitter"
require "user.theme"
require "user.copilot"
require "user.cmp"
require "user.lsp"
require "user.rust-tools"
require "user.dap"
require "user.fterm"
--require "user.toggleterm"
require "user.hop" -- easymotion alternative
require "user.close-buffer"
